### ISSUE TITLE
Build project using Makefile inside CodeLite doesn't work 

### ISSUE THREAD

**Issue by sirbugur** [REEF3D/REEF3D#12]
**Describe the bug**
According to the documentation issued for REEF3D v.21.05 section "3.3 Developer Installation : CodeLite", configuration of the active workspace is defined as follows:
> • For DIVEMesh:
  Build: make -f ../Makefile -j N (with N at least the number of available cores) 
  Clean: make -f ../Makefile clean (with N at least the number of available cores) 
  Rebuild: make -f ../Makefile -j N (with N at least the number of available cores)
  • For REEF3D:
  Build: make -f ../Makefile -j N (with N at least the number of available cores) 
  Clean: make -f ../Makefile clean (with N at least the number of available cores) 
  Rebuild: make -f ../Makefile -j N (with N at least the number of available cores)

At the moment, this procedure is working for DIVEMesh but not working for REEF3D. The reason for this bug can be found in the following commit:
https://github.com/REEF3D/REEF3D/commit/467e972a89633f7bae07298a465360aeb1d2ce60#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

**Expected behavior**
Please kindly revise the relevant part of the document as follows for consistency:

> Workspace > Open Active Project Settings > Customize > Enable custom build
Point the working directory to the **_main_** code folder and set the target commands as:
• For DIVEMesh:
Build: make -j N (with N at least the number of available cores) 
Clean: make clean (with N at least the number of available cores) 
Rebuild: make -j N (with N at least the number of available cores)
• For REEF3D:
Build: make -j N (with N at least the number of available cores) 
Clean: make clean (with N at least the number of available cores) 
Rebuild: make -j N (with N at least the number of available cores)

In order to this revision to be valid, line 4 of DIVEMesh/Makefile should be amended as follows:
` (-) CXX      := -g++`
` (+) CXX      := g++`

**System information:**
 - REEF3D v.21.05
 - DIVEMesh v.21.05
 - OS MacOS

**Comment by hansbihs** [comment]
Codelite generates its own makefiles ("REEF3D.mk") and not the one found in the main REEF3D folder. So there is nothing from our side to do. For me, Codelite works without problem.
