### ISSUE TITLE
Unused Parameters - Flow around Circular Pier

### ISSUE THREAD

**Issue by IADInocencio** [REEF3D/REEF3D#16]
In the provided ctrl.txt for 8_5 Flow around a Circular Pier there is a "B 11" on the second row.  This doesn't show up in Section 9.5.2 User Guide (page 115/144) and is also not mentioned in Section 2.2.

Similar for "I 20 1500" on row 12 of ctrl.txt; it is not in the user guide.

Version 21.10

**Comment by TobiasMartin** [comment]
Thank you very much for the hint. The mistakes are corrected in the latest version.
