### ISSUE TITLE
A confused output in sediment_log.cpp

### ISSUE THREAD

**Issue by AlKukharskii** [REEF3D/REEF3D#32]
**Describe the bug**
Order of variables was confused in sediment_log.cpp. 
File "sediment_log.cpp", method "log_ini", line 39:    
sedlogout<<"#iteration \t #simtime  \t #dtsed \t| #sedtime \t #sediter \t #slidecells \t| #bedmin \t #bedmax \t|"<<endl;
and order in method "sedimentlog" is:
sedlogout<<p->count<<"\t \t \t";
    sedlogout<<setprecision(4)<<p->dtsed<<" \t ";
    sedlogout<<setprecision(5)<<p->simtime<<" \t ";
    sedlogout<<setprecision(4)<<p->sedtime<<" \t ";
    sedlogout<<setprecision(4)<<p->sediter<<" \t ";
    sedlogout<<setprecision(4)<<p->slidecells<<" \t ";

    sedlogout<<setprecision(4)<<p->bedmin<<" \t ";
    sedlogout<<setprecision(4)<<p->bedmax<<" \t "<<endl;

As you can see, "simtime" and "dtsed" is confused in method "log_ini", line 39.

**Expected behavior**
I suggest to replace "simtime" with "dtsed" and vice versa.

**System information:**
 - REEF3D 23.03
 - DIVEMesh 23.03
 - OpenMPI version 
 - Hypre 2.29.0 
 - OS Ubuntu

![Screenshot from 2023-07-14 11-38-57](https://github.com/REEF3D/REEF3D/assets/86282638/215d0bf4-fe77-4cec-ac19-dce2d4e5ca77)

**Comment by hansbihs** [comment]
Thanks for the feedback! Fixed in latest RC.
