### ISSUE TITLE
Bug in Sediment Initialization with Potential Flow

### ISSUE THREAD

**Issue by AlKukharskii** [REEF3D/REEF3D#33]
**Describe the bug**
In case if you initialize a sediment model with  a potential flow solver (I11 1 or 2) then the density of air (W3) is used for shear bed calculations instead of the density of water (W1). Nevertheless, the CRITICAL shear bed is being calculated with the density of water (W1). In case of pressure initialization (I12) everything works fine.

**In more details:**
I have localized a problem in a file bedshear.cpp, method taubed() line 59:
density = a->ro(i,j,k);

Here, density reads W3 instead of W1 in the described above circumstances.  Unfortunately, I have not found the core of the problem yet.

**Expected behavior**
It is expected that it will read W1 density instead of W3.

**System information:**
Originally problem was found in REEF3D 23.01 and DiveMesh 23.01. Later, I have found the same problem in REEF3D 23.03 and DiveMesh 23.03
 - OpenMPI version 4.1.2
 - Hypre version 2.28
 - OS Ubuntu 22.04

**Attachment**
I also attach the working case Test_Work and a case which demonstrates this error (Test_Broke). Also I add a screenshot which demonstrates the used values of the density in the file bedshear.cpp.

[Test_Broken.zip](https://github.com/REEF3D/REEF3D/files/12213373/Test_Broken.zip)
[Test_Work.zip](https://github.com/REEF3D/REEF3D/files/12213374/Test_Work.zip)
![Screenshot from 2023-07-31 12-08-56](https://github.com/REEF3D/REEF3D/assets/86282638/1afd9191-6553-4ca2-b63a-bbfcba817f57)

**Comment by hansbihs** [comment]
Thanks for the feedback!

Yes, the density is zero - but only before the sediment transport calculation starts because bedk(i,j) is still zero. It does not effect the actual sediment transport calculation. Fixed in newest RC.
