### ISSUE TITLE
Need help in running simulation

### ISSUE THREAD

**Issue by Subhash9999999** [REEF3D/REEF3D#64]
**Describe the bug**

**Expected behavior**

**System information:**
 - REEF3D version
 - DIVEMesh version
 - OpenMPI version 
 - Hypre version 
 - OS [e.g. Windows, Ubuntu, MacOS]

**Attachment**
Please attach the control files which produce the bug.

**Comment by AlHanke** [comment]
Check section 5 of the user guide for information on running REEF3D.
