### ISSUE TITLE
Initial linear velocity for floating body is ignored?

### ISSUE THREAD

**Issue by albertoferna** [REEF3D/REEF3D#9]
Hello,

First of all congratulations on a very interesting looking solver.

I'm trying to run a validation case. It is just a cylinder drop to compare with an experiment (as a 2d case so far).
I want to set an initial drop velocity in order to run for a smaller time. I used the following ctrl.txt file, but it looks like X 102 is being ignored.

Am I looking at this wrong or is X 102 not working?
The cylinder is an stl file in this case. But, I have also tried using X 132 with the same result. The case looks like it runs, but the staring velocity is 0

**Comment by TobiasMartin** [comment]
Hi,
X 102 should generally work. But to give you a more detailed advice, you have to send us your control files. You could also try using X 13 2.

**Comment by albertoferna** [comment]
Using X 13 2 works. I have velocities exceeding the critical value now, but that I have to review. I need to play around with the numerics.

However, using X 13 would force the speed to be constant if I'm not mistaken. I'd like to have the disk in free fall for comparison with the experiment.
This is my control file in case it is of use:
```
D 10 4
D 20 2
D 30 1

F 30 3
F 40 7
F 50 4
F 56 0.6
I 12 1
N 10 14
N 11 11
N 40 1
N 41 0.1
N 45 50
N 47 0.1

P 10 1
P 25 1
P 30 0.0005

W 22 -9.81
X 10 1
X 11 0 0 1 0 0 0
X 12 1
X 21 1500
X 33 2
X 34 1
X 102 0.0 0.0 -4.0

X 180 1
```
Thank you for your time
